services:
  recircle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recircle_app
    command: python main.py
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db
    volumes:
      - .:/app
    restart: on-failure

  db:
    image: postgres:15
    container_name: recircle_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recircle
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
